# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6d13603d284b661acef6448ed27c282bfa87e4d84d9b53df7c3657d57ba8c146defa4a6989288c5e470a71c9f6a360448a3ebaac1efdff01f0b66b0c9c294175

# Use different runs of `rake secret` for development and test
test:
  secret_key_base: 3af16d9896d92f0ffa0086ac33911a3edea2b08bbcbc4ce6bb629a31864b85a6e4bb0a92cd167bdf46aa08c171d38d31f0f16d8771876ce4600885de974f78da

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
